### ISSUE TITLE
ios端打包报错 'libpag/PAGPlayer.h' file not found

### ISSUE THREAD

**Issue by tasselx** [libpag/pag-ios#10]
![image](https://user-images.githubusercontent.com/2656142/198583758-c7716654-df0e-4ab6-bf69-c94b798d5d5d.png)

**Comment by ZzOoz** [comment]
请问解决了吗？

**Comment by ZzOoz** [comment]
想请教一下怎么解决的？

**Comment by tasselx** [comment]
@ZzOoz 解决了，新更新的少armv7的支持
